"""assets

Revision ID: 53db5f91ec72
Revises: ccd1d8c9d36c
Create Date: 2026-09-29 12:14:38.235832

"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53db5f91ec72'
down_revision: str | Sequence[str] | None = 'ccd1d8c9d36c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('pdf', 'video', 'submission', 'certificate', 'image', name='asset_kind'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.add_column('lessons', sa.Column('video_asset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('lessons_video_asset_id_fkey', 'lessons', 'assets', ['video_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lessons_video_asset_id_fkey', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'video_asset_id')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_table('assets')
    op.execute("DROP TYPE IF EXISTS asset_kind")
    # ### end Alembic commands ###
