"""sources unique lesson asset

Revision ID: 59f0a33a0060
Revises: aa608bdc6a4e
Create Date: 2026-09-29 15:17:24.971375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '59f0a33a0060'
down_revision: Union[str, Sequence[str], None] = 'aa608bdc6a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sources_lesson_asset', 'sources', ['lesson_id', 'asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sources_lesson_asset', 'sources', type_='unique')
    # ### end Alembic commands ###
