"""lesson video index

Revision ID: 6d5e18d98e86
Revises: 53db5f91ec72
Create Date: 2026-09-29 12:46:46.199146

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d5e18d98e86"
down_revision: str | Sequence[str] | None = "53db5f91ec72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_lessons_video_asset_id"), "lessons", ["video_asset_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lessons_video_asset_id"), table_name="lessons")
    # ### end Alembic commands ###
