"""jobs

Revision ID: e6196694c937
Revises: 6d5e18d98e86
Create Date: 2026-09-29 12:58:47.762910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'e6196694c937'
down_revision: Union[str, Sequence[str], None] = '6d5e18d98e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=False),
    sa.Column('ref_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_job', 'jobs', ['type', 'ref_id', 'ref_version'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_job', table_name='jobs', postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_table('jobs')
    op.execute("DROP TYPE IF EXISTS job_status")
    # ### end Alembic commands ###
